### ISSUE TITLE
module definitions in angular.json

### ISSUE THREAD

**Issue by yvz5** [lmeijdam/angular-umd-dynamic-example#6]
i found module definitions in the angular.json file. isnt this against the idea of a plugin system ? if these modules are unknown at compile time, how does it help to put modules there ?

![image](https://user-images.githubusercontent.com/439370/52550618-1978a180-2dd9-11e9-8793-6f53aca5cae0.png)

**Comment by LeoLetourneur** [comment]
This is just some configs to build UMD modules. To build a module, you need an "angular app", so instead of using a second app, you can build directly in your main app. But your main app will not include these modules in the build.

If someone else create a new module without your main app, he will have to create a new "app" just for building the new module.

**Comment by yvz5** [comment]
ok got it thanks.
